server:
  port: 8100

spring:
  application:
    name: devsu-client-person-api
  mvc:
    servlet:
      path: /devsu/mscliper
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: somePassword
  hikari:
    maximum-pool-size: 2
    pool-name: OrionPool
    max-lifetime: 30000
    minimum-idle: 1
    idle-timeout: 0
